-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

-- Type: status

-- DROP TYPE IF EXISTS public.status;

CREATE TYPE public.status AS ENUM
    ('draft', 'pending', 'paid');

ALTER TYPE public.status
    OWNER TO supabase_admin;

-- Type: item

-- DROP TYPE IF EXISTS public.item;

CREATE TYPE public.item AS
(
	name text,
	quantity integer,
	price double precision,
	total double precision
);

ALTER TYPE public.item
    OWNER TO supabase_admin;

-- Type: address

-- DROP TYPE IF EXISTS public.address;

CREATE TYPE public.address AS
(
	street text,
	city text,
	postcode text,
	country text
);

ALTER TYPE public.address
    OWNER TO supabase_admin;